version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hostdesign-web
    restart: unless-stopped
    ports:
      - "30000:3000"
    networks:
      - new-hostdesign-network

networks:
  new-hostdesign-network:
    external: true
